Evaluate directives in _JobOperation Constructor
glotzerlab/signac-flow pull request #409
Opened 2020-12-22 22:38 UTC by b-butler

## Description

Evaluate the directives in the `_JobOperation` constructor. This should fix #408. This does mean that all directives will be evaluated at the construction of `_JobOperation`. I don't think this should pose any problems, and indeed it should have been evaluated there to begin with since we change class in `_JobOperation`.

## Motivation and Context

Fixes #408.

## Types of Changes

- [ ] Documentation update
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

2020-12-23 01:35 UTC, bdice requested changes
@b-butler It looks like this might fix the problem, but I am worried about the duplication between `_JobOperation` and `JobOperation`. I asked a while back about whether we could safely merge the two classes (so that the deprecated public class would call the private class's constructor via `super().__init__(...)` instead of having repeated logic. I believe that may be important, since I don't see a similar `directives.evaluate(jobs)` call in the public class's constructor. Would you be able to take a look into consolidating that?

2020-12-23 16:59 UTC, b-butler commented
@bdice Can do.

2020-12-25 07:08 UTC, bdice requested changes
@b-butler These changes look good. One more request; would it be possible to add a test that catches the problem in #408?

2020-12-31 15:21 UTC, b-butler commented
@bdice, the code coverage tests are failing due to the change in `JobOperation`'s constructor. I don't think like adding tests for specifically for a deprecated class that no one is likely using necessary, but if you feel it is, I can add tests specifically for that so the code coverage tests pass.

2020-12-31 16:18 UTC, bdice commented
> @bdice, the code coverage tests are failing due to the change in `JobOperation`'s constructor. I don't think like adding tests for specifically for a deprecated class that no one is likely using necessary, but if you feel it is, I can add tests specifically for that so the code coverage tests pass.

@b-butler I wasn’t worried about code coverage as a number - I was concerned that the issue #408 might not be covered by tests. This fix is good but only if we can prevent the problem from happening again. In my understanding that’s independent of whether the public/deprecated class or private class is used. Is that right?

2020-12-31 18:43 UTC, bdice approved these changes
I have a couple small suggestions that I will apply directly. This PR looks good, thanks for the fix!

2020-12-31 18:43 UTC, bdice commented on changelog.txt
> +- Ensure that directives are always evaluated before running or submitting (#408).
```suggestion
- Ensure that directives are always evaluated before running or submitting (#408, #409).
```

2020-12-31 18:43 UTC, bdice commented on flow/project.py
> +        all callable directives should be evalauted to concrete value).
```suggestion
        all callable directives should evaluate to concrete values).
```

2020-12-31 18:43 UTC, bdice commented on tests/test_project.py
> +            [job], project._get_default_directives()
The internals work differently on `next`, so we'll need to adjust this test when merging it with `next`. This PR currently targets `master` so this shouldn't be applied yet.
```suggestion
            [(job,)], project._get_default_directives()
```

2021-01-02 04:01 UTC, merged