converting to int
glotzerlab/signac-flow pull request #484
Opened 2021-03-23 13:43 UTC by atravitz

## Description
Fixes #482 

## Motivation and Context

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [ ] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [ ] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

2021-03-23 13:58 UTC, b-butler approved these changes
LGTM

2021-03-23 14:13 UTC, bdice commented
@atravitz @b-butler This would not correctly handle a request of `"512m"` -- it would convert to gigabytes and round down to zero.

2021-03-23 14:13 UTC, bdice requested changes
@atravitz @b-butler This would not correctly handle a request of "512m" -- it would convert to 0.5 gigabytes and round down to zero.

Options, in order of my preference:
1. Convert non-integer values into megabytes.
2. Round up to the next integer (doesn't actually obey user request).
3. Disallow non-integer values (require input to be an integer number of gigabytes).

2021-03-23 15:32 UTC, tommy-waltmann commented
I like the first option a lot better than the other two.

2021-03-23 15:44 UTC, b-butler commented
@bdice I wasn't aware that we were allowing non-gigabyte specifications. In that case number 1 seems appropriate.

2021-03-23 16:01 UTC, kidrahahjo commented
I had the same concern as @bdice mentioned when I reviewed #483. Before we make any change in this regard, we should definitely test the code on the clusters we support and then decide to generalise this.

2021-03-23 17:35 UTC, vyasr commented
I've typically seen <1 Gb requests specified in Mb, not in fractional Gb. I think specification in Mb is much more familiar to users than fractional Gb, so we should definitely support that.

2021-03-25 15:50 UTC, csadorf commented
Let's make sure to use the correct prefix here ([GiB](https://en.wikipedia.org/wiki/Gigabyte#Base_2_(binary)) vs [GB](https://en.wikipedia.org/wiki/Gigabyte#Base_10_(decimal))! See also [_Understanding the difference between GB and GiB_](https://docs.ukcloud.com/articles/other/other-ref-gib.html).

2021-03-25 21:26 UTC, vyasr commented
> Let's make sure to use the correct prefix here ([GiB](https://en.wikipedia.org/wiki/Gigabyte#Base_2_(binary)) vs [GB](https://en.wikipedia.org/wiki/Gigabyte#Base_10_(decimal)))! See also: [_Understanding the difference between GB and GiB_](https://docs.ukcloud.com/articles/other/other-ref-gib.html).

Fair point. I think most official documents describing schedulers either spell out "gigabyte" or just use G, while most unofficial documents I've read (like the [Great Lakes user guide](https://arc.umich.edu/greatlakes/user-guide/)!) use the base 10 and base 2 equivalents freely without clarification. We may as well be precise in our discussions though.

I think your comment mostly applies to my previous comment 🙃. Everywhere in the code regarding directives I think it's just a single-letter prefix "G" or "g".

2021-03-26 08:53 UTC, csadorf commented
Yeah, I think using `G` as an ambiguous abbreviation is fine as long as it is clearly documents what it refers to and then make the appropriate conversion. Ideally we support the full unit symbol as well.

2021-04-01 16:52 UTC, bdice approved these changes
Good! Just needs an updated comment.

2021-04-01 16:52 UTC, bdice commented on flow/util/template_filters.py
> +    -------"""
```suggestion
    """Format memory request as a string with an appropriate suffix.
    
    Parameters
    -----------
    memory : float
        Value of memory to format in gigabytes.

    Returns
    -------
    str
        String value with suffix "G" or "M".
    """
```

2021-04-02 16:52 UTC, bdice approved these changes
Thanks @atravitz! This looks good to me.

2021-04-02 16:54 UTC, bdice commented
@tommy-waltmann @b-butler @klywang This can be merged once we get a second review. (@b-butler I dismissed your first review approval because the PR has changed substantially since then.)

2021-04-02 17:01 UTC, bdice commented
> 
> 
> Yeah, I think using `G` as an ambiguous abbreviation is fine as long as it is clearly documented what it refers to and then make the appropriate conversion. Ideally we support the full unit symbol as well.

@csadorf Do you mean we should support "GB" as an input for the directive? This would be fine to support but I think it's out of scope for this PR. Feel free to create an issue!

2021-04-02 20:30 UTC, tommy-waltmann approved these changes

2021-04-02 20:49 UTC, merged